### ISSUE TITLE
Move dialog out of center

### ISSUE THREAD

**Issue by pkasson** [mjn1369/PrettyDialog#1]
Is it possible to pass in a parameter to adjust the Y position of the dialog ?  At times, the content behind the UI is overlaid with the dialog and moving the dialog up or down would provide that information so the user can see what they are agreeing to, or not.

**Comment by mjn1369** [comment]
Thanks for your feedback. I'll provide the GRAVITY attribute in next version to handle this kind of situations.

**Comment by mjn1369** [comment]
Added "setGravity(int gravity)" method in v1.0.1
