### ISSUE TITLE
prettyDialog.setIconTint did not work on version api 21 or below

### ISSUE THREAD

**Issue by tohami** [mjn1369/PrettyDialog#3]
i try to change the icon using the set icon 
`prettyDialog.setIcon(R.drawable.shopping_bag , R.color.ecomerce_green, null);`

but it did not work with me 
i use 
`  prettyDialog.setIconTint(R.color.ecomerce_green) ;
`
also it did not work

**Comment by tohami** [comment]
`public PrettyDialog setIconTint(Integer color) {
        this.iv_icon.setColorFilter(ContextCompat.getColor(this.context, (color == null?this.default_icon_tint:color).intValue()), Mode.MULTIPLY);
        return this;
    }`

you use this to change the color of icon 
i android developer site it say 

> 
Starting in M, the returned color will be styled for the specified Context's theme.
> 

>

**Comment by mjn1369** [comment]
I've changed setTint() methods to be compatible with previous versions.
