### ISSUE TITLE
can you add create if long message

### ISSUE THREAD

**Issue by fajaranugrah** [mjn1369/PrettyDialog#4]
hello sir 
can you create if the message is too long or large on font phone size?

thank you

**Comment by fajaranugrah** [comment]
If the device font size changed then the dialog doesn't scroll text, also the button doesn't appear to dismiss or do other action.

![image](https://user-images.githubusercontent.com/38461162/43438080-05c80756-94bf-11e8-91b7-a2a8d1f1a9fa.png)

![image](https://user-images.githubusercontent.com/38461162/43438127-3ad0b47a-94bf-11e8-9cf7-2a8f586ce651.png)

**Comment by mjn1369** [comment]
I'll check into that ASAP

**Comment by mjn1369** [comment]
@fajaranugrah you can grab v1.0.3 now. It should be fixed.

**Comment by fajaranugrah** [comment]
@mjn1369 thank you
