### ISSUE TITLE
How to create if not using icon Tint Color

### ISSUE THREAD

**Issue by fajaranugrah** [mjn1369/PrettyDialog#5]
Hello sir
may i know how to not using Tint icon Color? because i want to using image on the setIcon
thank you

**Comment by mjn1369** [comment]
Hello
Sorry but that place should only be filled by an icon, not an image. And icons should have a tint otherwise the default color (blue) will be applied.

**Comment by mjn1369** [comment]
hello
I removed the default tint color and added circularity to icon's imageview
you can grab v1.0.4 now

**Comment by fajaranugrah** [comment]
thank you
